# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/application'

task default: :test

desc 'Update README.md with The Latest Output from The Application'
Rake::Task.define_task(:update_readme) do
  puts '========== Start Updating README ==========='
  Application.run
  puts '========== Finished Updating README ==========='
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
